name: Validate JSON

on: [pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate JSON
        run: |
          for file in $(find ./data -name '*.json'); do
            echo "Validating $file"
            python3 -m json.tool < "$file" > /dev/null || exit 1
          done
